### ISSUE TITLE
Version 1.1 is not available

### ISSUE THREAD

**Issue by sorcererxw** [TelegramMessenger/TGPassportAndroidSDK#3]
I can only find TGPassportAndroidSDK:1.0 on mavenCentral

**Comment by grishka** [comment]
Yeah, it doesn't show up on search.maven.org, even though I'm sure I pushed it and did everything exactly the way I did when I first released it. I'll try pushing it again.

**Comment by grishka** [comment]
Should be available now https://oss.sonatype.org/content/groups/public/org/telegram/passport/1.1/
